# Generated by Django 5.1 on 2024-11-24 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(help_text="Spotify's unique identifier for the user (alphanumeric string)", max_length=100, unique=True)),
                ('spotify_username', models.CharField(blank=True, help_text="User's Spotify username", max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, help_text="User's display name on Spotify", max_length=100, null=True)),
                ('external_url', models.URLField(blank=True, help_text="URL to user's Spotify profile", null=True)),
                ('profile_image_url', models.URLField(blank=True, help_text="URL to user's Spotify profile image", null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('top_tracks', models.JSONField(default=list, help_text="User's top tracks from Spotify")),
                ('top_artists', models.JSONField(default=list, help_text="User's top artists from Spotify")),
                ('recent_tracks', models.JSONField(default=list, help_text="User's recently played tracks")),
                ('saved_albums', models.JSONField(default=list, help_text="User's saved albums")),
                ('saved_tracks', models.JSONField(default=list, help_text="User's saved tracks")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spotify User',
                'verbose_name_plural': 'Spotify Users',
            },
        ),
    ]
