# Generated by Django 5.1 on 2024-12-02 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyWrapped', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='spotify_id',
            field=models.CharField(help_text="Spotify's unique identifier for the user", max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='SpotifyWrapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(choices=[('short_term', 'Past 3 Months'), ('medium_term', 'Past 6 Months'), ('long_term', 'Past 12 Months')], max_length=20)),
                ('top_track_name', models.CharField(blank=True, max_length=200, null=True)),
                ('album_cover_url', models.URLField(blank=True, null=True)),
                ('wrapped_name', models.CharField(default='Untitled Wrapped', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_wraps', to='spotifyWrapped.spotifyuser')),
            ],
        ),
    ]
