# Generated by Django 5.1 on 2024-10-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyWrapped', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
